import { promises as fs } from 'fs';
import path from 'path';
import { pathToFileURL } from 'url';

async function main() {
  const root = process.cwd();
  const apiDir = path.join(root, 'docs', 'generated', 'api');

  await fs.rm(apiDir, { recursive: true, force: true });
  await fs.mkdir(apiDir, { recursive: true });
  await writeCommandApiPage(apiDir);
}

async function writeCommandApiPage(apiDir) {
  const { commands, program } = await loadCommandApiRuntime();
  const commandsPath = path.join(apiDir, 'commands.md');
  await fs.writeFile(commandsPath, `${[
    '---',
    'title: Command API',
    'outline: deep',
    '---',
    '',
    '<!-- Generated by scripts/postprocess-docs.mjs. Do not edit by hand. -->',
    '',
    '# Command API',
    '',
    'Ashiba command contracts are exposed by the same CLI command catalog used by `ashiba describe command` and command help.',
    '',
    'This page is for third-party readers who need to understand what commands exist, when to use them, and what their arguments and options mean.',
    '',
    'Each command section includes the real Commander help output so the docs do not maintain a separate argument or option explanation.',
    '',
    '```bash',
    'npx ashiba --help',
    'npx ashiba <command> --help',
    'npx ashiba describe command --format json',
    '```',
    '',
    '## Command List',
    '',
    ...commands.flatMap((command) => renderCommandSpec(command, program)),
  ].join('\n')}`, 'utf8');
  console.log('[postprocess-docs] Wrote generated/api/commands.md');
}

async function loadCommandApiRuntime() {
  const root = process.cwd();
  const catalogPath = path.join(root, 'packages', 'cli', 'dist', 'commands', 'command-catalog.js');
  const indexPath = path.join(root, 'packages', 'cli', 'dist', 'index.js');
  await assertFileExists(catalogPath, 'Run `pnpm --filter @ashiba/cli build` before generating docs.');
  await assertFileExists(indexPath, 'Run `pnpm --filter @ashiba/cli build` before generating docs.');
  const [catalogModule, cliModule] = await Promise.all([
    import(pathToFileURL(catalogPath).href),
    import(pathToFileURL(indexPath).href),
  ]);
  return {
    commands: catalogModule.COMMANDS,
    program: cliModule.buildProgram(),
  };
}

async function assertFileExists(filePath, nextAction) {
  try {
    await fs.access(filePath);
  } catch {
    throw new Error(`Missing required CLI build artifact: ${path.relative(process.cwd(), filePath)}. ${nextAction}`);
  }
}

function renderCommandSpec(command, program) {
  const help = getCommandHelp(program, command.name);
  return [
    `## npx ashiba ${command.name}`,
    '',
    command.summary,
    '',
    `**Use when:** ${command.useCase}`,
    '',
    '**CLI Help**',
    '',
    '```text',
    help.trimEnd(),
    '```',
    '',
  ];
}

function getCommandHelp(program, name) {
  const command = findCommand(program, name);
  if (!command) {
    throw new Error(`Command registered in catalog but missing from CLI help: ${name}`);
  }
  return captureCommandHelp(command);
}

function findCommand(program, name) {
  const parts = name.split(' ');
  let current = program;
  for (const part of parts) {
    current = current.commands.find((command) => command.name() === part);
    if (!current) {
      return undefined;
    }
  }
  return current;
}

function captureCommandHelp(command) {
  let output = '';
  command.configureOutput({
    writeOut: (text) => {
      output += text;
    },
    writeErr: (text) => {
      output += text;
    },
  });
  command.outputHelp();
  return output;
}

main().catch((error) => {
  console.error('[postprocess-docs] Failed with error:', error);
  process.exitCode = 1;
});
