import { promises as fs } from 'fs';
import path from 'path';
import { pathToFileURL } from 'url';

async function main() {
  const root = process.cwd();
  const apiDir = path.join(root, 'docs', 'generated', 'api');

  await ensureIndexFrontMatter(apiDir);
  await writeCommandApiPage(apiDir);
  await wrapMarkdownWithVPre(apiDir);
}

async function ensureIndexFrontMatter(apiDir) {
  const indexPath = path.join(apiDir, 'README.md');
  const targetPath = path.join(apiDir, 'index.md');

  let source = indexPath;
  try {
    await fs.access(indexPath);
  } catch {
    source = targetPath;
  }

  try {
    await fs.access(source);
  } catch {
    console.warn('[postprocess-docs] index markdown not found, skipping front matter injection');
    return;
  }

  if (source === indexPath) {
    await fs.rename(indexPath, targetPath);
  }

  const content = await fs.readFile(targetPath, 'utf8');
  if (!content.trimStart().startsWith('---')) {
    const frontMatter = ['---', 'title: API Overview', 'outline: deep', '---', ''].join('\n');
    await fs.writeFile(targetPath, frontMatter + content, 'utf8');
    console.log('[postprocess-docs] Injected front matter into generated/api/index.md');
  }
}

async function writeCommandApiPage(apiDir) {
  const { commands, program } = await loadCommandApiRuntime();
  const commandsPath = path.join(apiDir, 'commands.md');
  await fs.writeFile(commandsPath, `${[
    '---',
    'title: Command API',
    'outline: deep',
    '---',
    '',
    '<!-- Generated by scripts/postprocess-docs.mjs. Do not edit by hand. -->',
    '',
    '# Command API',
    '',
    'Ashiba command contracts are exposed by the same CLI command catalog used by `ashiba describe command` and command help.',
    '',
    'This page is for third-party readers who need to understand what commands exist, when to use them, and what their arguments and options mean.',
    '',
    'The lower-level TypeScript API reference is also generated, but pages such as `cli/src/functions/main` describe exported implementation functions, not the CLI command contract.',
    '',
    'Each command section includes the real Commander help output so the docs do not maintain a separate argument or option explanation.',
    '',
    '```bash',
    'npx ashiba --help',
    'npx ashiba <command> --help',
    'npx ashiba describe command --format json',
    '```',
    '',
    '## Command List',
    '',
    ...commands.flatMap((command) => renderCommandSpec(command, program)),
  ].join('\n')}`, 'utf8');
  console.log('[postprocess-docs] Wrote generated/api/commands.md');
}

async function loadCommandApiRuntime() {
  const root = process.cwd();
  const catalogPath = path.join(root, 'packages', 'cli', 'dist', 'commands', 'command-catalog.js');
  const indexPath = path.join(root, 'packages', 'cli', 'dist', 'index.js');
  const [catalogModule, cliModule] = await Promise.all([
    import(pathToFileURL(catalogPath).href),
    import(pathToFileURL(indexPath).href),
  ]);
  return {
    commands: catalogModule.COMMANDS,
    program: cliModule.buildProgram(),
  };
}

function renderCommandSpec(command, program) {
  const help = getCommandHelp(program, command.name);
  const lines = [
    `## npx ashiba ${command.name}`,
    '',
    command.summary,
    '',
    `**Use when:** ${command.useCase}`,
    '',
    '**CLI Help**',
    '',
    '```text',
    help.trimEnd(),
    '```',
    '',
  ];

  return lines;
}

function getCommandHelp(program, name) {
  const command = findCommand(program, name);
  if (!command) {
    throw new Error(`Command registered in catalog but missing from CLI help: ${name}`);
  }
  return captureCommandHelp(command);
}

function findCommand(program, name) {
  const parts = name.split(' ');
  let current = program;
  for (const part of parts) {
    current = current.commands.find((command) => command.name() === part);
    if (!current) {
      return undefined;
    }
  }
  return current;
}

function captureCommandHelp(command) {
  let output = '';
  command.configureOutput({
    writeOut: (text) => {
      output += text;
    },
    writeErr: (text) => {
      output += text;
    },
  });
  command.outputHelp();
  return output;
}

async function wrapMarkdownWithVPre(dir) {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      await wrapMarkdownWithVPre(fullPath);
      continue;
    }
    if (!entry.name.endsWith('.md')) {
      continue;
    }

    const original = await fs.readFile(fullPath, 'utf8');
    let frontMatter = '';
    let body = original;

    if (original.startsWith('---')) {
      const end = original.indexOf('\n---', 3);
      if (end !== -1) {
        frontMatter = original.slice(0, end + 4).trimEnd();
        body = original.slice(end + 4).replace(/^\s+/, '');
      }
    }

    const genericLineRE = /^(\s*[-*>+]?\s*)([^`\n<>]*?\b[A-Za-z0-9_$]+<[^>\n]+>[^`\n]*)$/gm;
    body = body.replace(genericLineRE, (match, prefix, content) => {
      const trimmed = content.trim();
      if (content.includes('`')) {
        return match;
      }
      return `${prefix}\`${trimmed}\``;
    });

    body = body.replace(/(?<=\b[A-Za-z0-9_$])<([^>\n]+)>/g, (_match, inner) => `&lt;${inner}&gt;`);
    body = body.replace(/\\<([^>\n]+)>/g, (_match, inner) => `&lt;${inner}&gt;`);

    const trimmedBody = body.trimStart();
    const hasWrapper = trimmedBody.startsWith('<div v-pre>') && trimmedBody.includes('</div>');

    if (hasWrapper) {
      const output = frontMatter ? `${frontMatter}\n\n${trimmedBody}\n` : `${trimmedBody}\n`;
      await fs.writeFile(fullPath, output, 'utf8');
      continue;
    }

    const wrappedBody = `<div v-pre>\n${body.trim()}\n</div>\n`;
    const output = frontMatter ? `${frontMatter}\n\n${wrappedBody}` : wrappedBody;
    await fs.writeFile(fullPath, output, 'utf8');
    console.log(`[postprocess-docs] Wrapped ${path.relative(dir, fullPath)} with <div v-pre> block`);
  }
}

main().catch((error) => {
  console.error('[postprocess-docs] Failed with error:', error);
  process.exitCode = 1;
});
